[tool.poetry]
name = "yz"
version = "0.1.0"
description = ""
authors = ["Mustafa Guven, Vodafone <Mustafa.Guven@vodafone.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
